### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Nillerr** [mockative/mockative#10]

**Comment by vitorhugods** [comment]
Hello @Nillerr.

First: Congrats and thank you for the amazing tool you've created.

I have been flirting with the idea of helping out, starting in a couple of weeks. And I guess that helping with documentation is one way to get to know the project better before actively submitting changes.

Could you please help

**Comment by vitorhugods** [comment]
Hello @Nillerr.

First: Congrats and thank you for the amazing tool you've created.

I have been flirting with the idea of helping out, starting in a couple of weeks. And I guess that helping with documentation is one way to get to know the project better before actively submitting changes.

Could you please share what you are thinking about improving in the documentation? I find the current read-me quite extensive already. Maybe it would be a good time to move some things to the `Wiki` and split into sections for better navigation, or just split into different Markdown files?

**Comment by harmittaa** [comment]
I'd be interested in helping too, have you yet thought about the broad strokes when it comes to improving the docs?

**Comment by Nillerr** [comment]
Hey there. Thank you for showing your interest.

Honestly, I haven't given much thought to what exactly I would like the documentation to be. I have received feedback from the community that echos the point you make @vitorhugods - that the current README is actually quite effective at getting people up and running, and there really isn't much more to Mockative at the moment.

Using the wiki is a good idea. Unfortunately, at the moment, I really don't have an idea about what this "improved documentation" would look like 🙈

**Comment by aSemy** [comment]
Hi 👋 

Personally I find the readme brief, but a little confusing.  


For example, there are several references to `transformData`

https://github.com/mockative/mockative/blob/2a4a1811745c74108f8852c5a3da3eae1d41d5ad/README.md?plain=1#L118-L128

but I'm not clear about whether `fun2<Data, String>()` means. Is it a function that has one argument, `Data`, and returns `String`? Or a function with two arguments, `Data` and `String`?

I would like to see more standalone examples.


I can recommend [Kotlinx Knit](https://github.com/Kotlin/kotlinx-knit). The [Kotlinx Serialization docs](https://github.com/Kotlin/kotlinx.serialization/tree/master/docs) use it, and I've recently used Knit along with a a GitHub Pages project, so the docs are published https://adamko-dev.github.io/kotlinx-serialization-typescript-generator/docs/examples/basic-classes. The best advantage of Knit is that any code in the docs is automatically tested and kept up-to-date.

Another suggestion is https://github.com/mfwgenerics/kapshot, which I think would be similar, but I've not used it.
