### ISSUE TITLE
io.mockative.NoSuchMockException: Kotlin 2.0.0-RC2

### ISSUE THREAD

**Issue by Clemodd** [mockative/mockative#109]
My test is actually working with old kotlin version, but now, I have this error : 

A mock for the type SplashScreenRepository was not generated.

    Make sure the property holding the mock is annotated with @Mock:

        @Mock
        private val myMock = mock(classOf<SplashScreenRepository>())
    

io.mockative.NoSuchMockException: A mock for the type SplashScreenRepository was not generated.

    Make sure the property holding the mock is annotated with @Mock:

        @Mock
        private val myMock = mock(classOf<SplashScreenRepository>())
Is it the fault of version 2.0.0-RC2?

**Comment by riQQ** [comment]
See also #74

**Comment by olegivo** [comment]
Also the same result for Kotlin 2.0.10
