### ISSUE TITLE
Compiler error 'Unresolved reference' because mock class is not generated for mockable class

### ISSUE THREAD

**Issue by riQQ** [mockative/mockative#110]
Affected: Mockative version 2.2.0 and bae8a598e72d342dab1a14261d158c67591ab953 (head of main as of today)

No mock class is generated for a mockable classes that is not used directly as a mock but indirectly as a property of another mockable class that in turn is used as a property of the mocked class. This leads to the compiler error 'Unresolved reference'.

>\> Task :shared:compileTestKotlinJvm FAILED
> e: file:///<...>/mockative/shared/build/generated/ksp/jvm/jvmTest/kotlin/io/github/Level1Mock.kt:22:12 Unresolved reference: Level2Mock

Classes
```kotlin
@Mockable
class NestedObject (
    private val prop: Level1
)

@Mockable
class Level1 (
    private val prop: Level2
)

@Mockable
class Level2 (
    private val prop: Level3
)

@Mockable
class Level3 (
    private val prop: Int
)
```

Test code
```kotlin
import io.mockative.Mock
import io.mockative.classOf
import io.mockative.isMock
import io.mockative.mock
import kotlin.test.Test
import kotlin.test.assertTrue

class NestedObjectTests {
    @Mock
    val mock: NestedObject = mock(classOf<NestedObject>())

    @Test
    fun isMockEmptyClass() {
        assertTrue(isMock(mock))
    }
}
```

I'll send a PR for the failing test.

The issues seems to be the following commit, removing the recursion:

https://github.com/mockative/mockative/commit/1241ddf5ec3896ac14918bec4b2962d1f9ca9028#diff-18add74c4d1bc1a6c6e96b909a9174179f8806ba2ad93f5b174f10e7b67f993cR151-R153

```diff
         private fun List<ProcessableType>.flatten(): List<ProcessableType> {
-            return this.flatMap { type ->
-                listOf(type) + type.children.flatten()
-            }
+            return this + flatMap { type -> type.children }
         }
```

**Comment by kris098e** [comment]
Good catch! And thanks for the test

[This pr](https://github.com/mockative/mockative/pull/114) will fix the issue
