### ISSUE TITLE
[Feature] Support Kotlin 2

### ISSUE THREAD

**Issue by Nillerr** [mockative/mockative#116]
This issue aims to track the resources and steps necessary to support Kotlin 2 and the K2 compiler. The work for this effort is being performed in https://github.com/mockative/mockative/tree/kotlin-2.

### Reported Issues

- #74 
- #109

### Blocking issues

- https://github.com/google/ksp/issues/885
- https://github.com/google/ksp/issues/1823

### Challenges

K2 introduces [Separation of common and platform sources during compilation](https://kotlinlang.org/docs/whatsnew-eap.html#separation-of-common-and-platform-sources-during-compilation), which may be a breaking change for Mockative.

KSP2 introduces [New Multiplatform Processing Scheme](https://android-developers.googleblog.com/2023/12/ksp2-preview-kotlin-k2-standalone.html)

**Comment by Nillerr** [comment]
Unfortunately, it looks like the K2 compiler (and by extension Kotlin 2) will break functionality that Mockative relies on through the [Separation of common and platform sources during compilation](https://kotlinlang.org/docs/whatsnew-eap.html#separation-of-common-and-platform-sources-during-compilation) 😞...

What we can do to continue supporting mocking in Kotlin Multiplatform is by enforcing the use of a `@Mockable` annotation in the primary source set, which means code would be generated regardless of whether it's being tested or not. We may be able to mitigate this by introducing a Gradle plugin that can detect whether the Gradle tasks being executed contain a `KotlinTest` task and only generate code in that event. We might also have to ensure that the generated code is deleted whenever a `KotlinTest` Gradle task is not being executed, such that we don't end up including test-only code in the primary source set.

**Comment by Nillerr** [comment]
Since https://github.com/google/ksp/issues/1823 appears to be a blocking issue, and the resolution to that issue is targeting Kotlin 2.1, we may not be able to support Kotlin 2+ until this issue is addressed 😞... I will investigate alternatives.

**Comment by mustafaozhan** [comment]
> issue is targeting Kotlin 2.1

That hurts... 😞 

>  I will investigate alternatives.

Hope you will find something

**Comment by Nillerr** [comment]
> > issue is targeting Kotlin 2.1
> 
> That hurts... 😞
> 
> > I will investigate alternatives.
> 
> Hope you will find something

I'll explain why I haven't posted any progress updates. Supporting Kotlin 2.0 __while sticking with KSP__ requires a fundamental change in how mocks are generated - a change that may not be desirable and would be pointless if the issue is resolved in Kotlin 2.1.

### Sticking with KSP

The change I'm contemplating is to move the generation of mocks away from the `test` source set(s), and into the `main` source set(s), which should resolve the issue of mocks not being resolved across source sets, by generating mocks in the same source set as the type being mocked.

This presents the issue of those mocks being present in the main source set(s), which means they would be part of the final library artifact/binary - something that's quite different from how Mockative already works where mocks are generated as part of the `test` source set(s) and thus are not present in the final library artifact/binary.

To prevent those mocks from being present in the final library artifact/binary I could probably introduce logic that would run Mockative's Symbol Processor only if a `Test` task is being executed by Gradle, and would remove the generated mocks whenever a `Test` task is not being executed by Gradle.

To support that generation scheme, the following changes must be implemented:

- Add an annotation for mockable types. We could re-use the `@Mock` annotation or introduce a new `@Mockable` annotation. This is the least of the challenges and is already similar to what's required for mocking classes.
- Change Mockative to generate mocks for annotated types instead of annotated properties. This is a relatively small task compared to:
- Introduce a Gradle plugin to conditionally apply Mockative's Symbol Processor and ensure generated mocks are not present in the final artifact/binary when not under test.

Even doing this, without the KSP issues reported in this issue being resolved, we may still not be able to generate mocks for all supported platforms before Kotlin 2.1 😕

### Alternative

The more dire alternative is to rewrite Mockative as a Kotlin Compiler Plugin instead of a Kotlin Symbol Processor, but at that point, I may as well point you in the direction of [lupuuss/Mokkery](https://github.com/lupuuss/Mokkery) which appears to be exactly that - Kotlin Multiplatform mocking using a Kotlin Compiler Plugin.

**Comment by jadar** [comment]
Could you help us to understand why it's better to use KSP than a Kotlin Compiler Plugin? (Other than it being a pain to rewrite.) I have transitioned all my tests over to Mokkery for the time being (not very many at the moment...) I have always had issues with KSP in a Multiplatform environment, so it's not too much love lost there. But if there's some compelling reason to stick with Mockative/KSP, I'm game to hear it...

**Comment by glureau** [comment]
>To prevent those mocks from being present in the final library artifact/binary I could probably introduce logic that would run Mockative's Symbol Processor only if a Test task is being executed by Gradle, and would remove the generated mocks whenever a Test task is not being executed by Gradle.

That means calling `./gradlew check publish` would detect the tests and publish code with mocks. If you go that route you may want to prevent that and throw an error message "cannot test and publish at the same time". And then the original issue compiler issue leaks now in the CI files where gradle usage needs to be adjusted. That's the very inconvenient, I prefer to wait until 2.1

**Comment by Ynnck123** [comment]
> Since [google/ksp#1823](https://github.com/google/ksp/issues/1823) appears to be a blocking issue, and the resolution to that issue is targeting Kotlin 2.1, we may not be able to support Kotlin 2+ until this issue is addressed 😞... I will investigate alternatives.

The issue seems to be fixed with https://github.com/google/ksp/pull/2103 and merged into main. So maybe with the next KSP release we have a solution ?

**Comment by Nillerr** [comment]
> > Since [google/ksp#1823](https://github.com/google/ksp/issues/1823) appears to be a blocking issue, and the resolution to that issue is targeting Kotlin 2.1, we may not be able to support Kotlin 2+ until this issue is addressed 😞... I will investigate alternatives.
> 
> The issue seems to be fixed with [google/ksp#2103](https://github.com/google/ksp/pull/2103) and merged into main. So maybe with the next KSP release we have a solution ?

That's exciting! I'll have a look once the fix hits a release of KSP.

**Comment by Nillerr** [comment]
Finally some fun news... I have made progress on supporting Kotlin 2!

It requires a small change to KSP, so I will submit a PR this week to address the symbol processor crashing issue.

I will also finally be adding a Gradle plugin so all you will have to do to use Mockative is:

```kotlin
plugins {
    id("io.mockative")
}
```

It will be a breaking change though - not to the API surface itself, but the `@Mock` annotation on properties will be replaced by a `@Mockable` annotation for the types you wish to generate mocks for. Special consideration has been taken to make sure mock generation is not enabled when a test task is not being run.

I expect to share a PR with support for all of this within this week and to merge it as soon as the necessary changes to KSP lands.

I understand that a lot of you depend on this project, and Kotlin 2 breaking the API was quite the blow to my joy of working on this project, but with these new changes, Mockative will act more like any other Kotlin Symbol Processor which should make it compatible with future changes to Kotlin.

**Comment by Nillerr** [comment]
I have just released Mockative 3 with support for Kotlin 2! I hope it will be a smooth transition for all, but should you notice any issues don't hesitate to submit an issue or contact me on the #kotlinlang Slack (https://kotlinlang.slack.com/team/U0N1TJZH8)
