### ISSUE TITLE
Error any.getKoin()

### ISSUE THREAD

**Issue by SirFilbido** [mockative/mockative#120]
Hello,

I'm trying to create unit tests for my classes and I'm also using Koin in the lazy classes and not via the primary constructor.

```kotlin
class ClientRestApi : KoinComponent {

    private val client by inject<ApiClient>()

    suspend fun validateDomain(domain: String): Flow<AppResponse<Client>> {
        return flowOf(client.getSafe<ClientResponse, Client>(
            url = "$CLIENT/$domain/$INFO",
            mapper = { it.toClient() }
        ))
    }

}
```

And when doing the test I'm getting an error where leaving my class open no longer occurs. But I believe that leaving the class open should not be mandatory

`This type is final, so it cannot be inherited from`

After "solving" and trying to do the test again, another error occurs, but related to Koin. Is there any way around this?

```
io.mockative.InvalidExpectationException: A function was called without a matching expectation.

    A coroutine stub was expected, but a blocking stub was configured on the function:
        Any.getKoin()

    Set up an expectation using:
        every { any.getKoin() }
            .invokes { ... }
    
    The following expectations were configured on the mock:
        getKoin()

```

**Comment by kris098e** [comment]
Hi @SirFilbido 

Please refer to the documentation for a suggested way of having your classes open only during tests [from here](https://github.com/mockative/mockative?tab=readme-ov-file#gradle-configuration-for-mocking-classes)

As for the `blocking stub` vs `coroutine stub`, you should set up the stub with `coEvery { ... }` instead of `every { ... }` if you have done so.

If I have misunderstood your last issue and my proposed solution does not work, could you please provide some code to reproduce the issue or some more context of your test code?

**Comment by SirFilbido** [comment]
Hello @kris098e,

I checked if I had correctly implemented the pre-configurations and in principle it was correct, but there was still an occasional error with the class not being opened.

Below is the improvement of the settings and the test example I am doing

`build.gradle.kts` - High level
``` kotlin
plugins {
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidLibrary) apply false
    alias(libs.plugins.jetbrainsCompose) apply false
    alias(libs.plugins.kotlinMultiplatform) apply false
    kotlin("plugin.allopen") version "1.9.23"
}

allOpen {
    annotation("kotlin.Metadata")
}

tasks.register("clean", Delete::class){
    delete(rootProject.layout.buildDirectory)
}
```

I believe that adding allOpen{...} after the plugins does not require the annotation class Mockable and its use in each class. So all my classes should be open when doing tests, right?


Example of a test I'm trying to run

```kotlin
import data.path.client.remote.ClientRestApi
import domain.AppResponse
import domain.path.client.model.Client
import io.mockative.Mock
import io.mockative.classOf
import io.mockative.coEvery
import io.mockative.mock
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.runBlocking
import kotlin.test.Test
import kotlin.test.assertEquals

class ClientRepositoryImplTest {

    @Mock
    val api = mock(classOf<ClientRestApi>())

    @Test
    fun `given a domain when validateDomain is called then return a valid Client`() {
        runBlocking {
            // Given
            val domain = "domain"
            val clientResponse =
                flow<AppResponse<Client>> { AppResponse.Success(Client("e26990d6", "domain", 42)) }
            coEvery { api.validateDomain(domain) }.returns(clientResponse)

            // When
            val result = api.validateDomain(domain)

            // Then
            assertEquals(result, clientResponse)
        }
    }

}
```

One point of attention, my project is pure KMP (old KMM) so all tests will be run in CommonTest and not on the native side

**Comment by kris098e** [comment]
I dont have much knowledge of `Koin`, but a fix would be to look into using the `KoinTest` provided by the framework, something like [this](https://medium.com/@maruchin/kmm-architecture-7-testing-93efd01f3952#:~:text=Classical%20Testing%20with%20Koin). Reading the article, you can register the generated Mockative mocks to be injected instead of the real instances, just like in the [Providing fakes with Koin](https://medium.com/@maruchin/kmm-architecture-7-testing-93efd01f3952#:~:text=Providing%20Fakes%20with%20Koin) section.

If it does not work, please also post the generated Mockative mock-class as I am not sure how it actually looks when using this approach :)

Feel free to reach out again!

**Comment by kris098e** [comment]
Do keep in mind on `Mockative`'s side, that for the `Koin` approach to work as specified by the example of `KoinTest`, the instances injected has to be initialized by the `mock()` function. Therefore it should not be enough using, for instance `ClientRestApi::class`, in the example step of _Providing Fakes with Koin_ in the article I linked to.

**Comment by SirFilbido** [comment]
I read the article and I believe it helped me solve part of it.

In this case, I used both Mockative and Koin for the tests.

```kotlin
class ClientRepositoryImplTest {

    @Mock
    private val api = mock(classOf<ClientRestApi>())

    @BeforeTest
    fun before() {
        startKoin {
            modules(appModule())
        }
    }

    @AfterTest
    fun after() {
        stopKoin()
    }

    @Test
    fun `given a domain when validateDomain is called then return a valid Client`() {
        runBlocking {
            // Given
            val domain = "domain"
            val clientResponse =
                flow<AppResponse<Client>> { AppResponse.Success(Client("e26990d6", "domain", 42)) }
            coEvery { api.validateDomain(domain) }.returns(clientResponse)

            // When
            val result = api.validateDomain(domain)

            // Then
            assertEquals(result, clientResponse)
        }
    }

}
```

I changed the "plugin.allopen" from build.gradle from project level to composeApp level, but the only thing I couldn't configure so that all my classes would be opened. Here is the before and after in the build.gradle composeApp level

Before
```kotlin
.
.
.
dependencies {
    configurations
        .filter { it.name.startsWith("ksp") && it.name.contains("Test") }
        .forEach { add(it.name, libs.mockative.processor) }
}

val taskIsRunningTest = gradle.startParameter.taskNames
    .any { it == "check" || it.startsWith("test") || it.contains("Test") }

if (taskIsRunningTest) {
    allOpen {
        annotation("app.Mockable")
    }
}
```

After
```kotlin
.
.
.
dependencies {
    configurations
        .filter { it.name.startsWith("ksp") && it.name.contains("Test") }
        .forEach { add(it.name, libs.mockative.processor) }
}

val taskIsRunningTest = gradle.startParameter.taskNames
    .any { it == "check" || it.startsWith("test") || it.contains("Test") }

if (taskIsRunningTest) {
    allOpen {
        annotation("kotlin.Metadata")
    }
}
```

**Comment by kris098e** [comment]
Nice that it worked

Regarding the _openess_, it seems that the [Metadata annotation is only present on the generated java classes](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-metadata/). So the correct way would be to use the canonical name of your own made annotation, like in the README describes in `Mockative`.

I will submit a PR to clarify this
