### ISSUE TITLE
Call for new maintainers

### ISSUE THREAD

**Issue by Nillerr** [mockative/mockative#129]
Over the past year or so it has become clear to me that I have lost most if not all my drive to work on this project. What started as an exciting project of using different technologies to solve an ancient problem for a new platform, has become more than a chore. I am proud of the work I have accomplished on Mockative, proud of the success of the project in reaching a lot of developers, and proud to have participated in the evolution of Kotlin Multiplatform, but as the issues keep piling up so do my feelings of neglect and dread for Mockative.

Since Mockative still has a significant userbase, instead of sunsetting the project entirely, I am calling for new maintainers to take over the project, so if you would like to pick up the torch and lead Mockative into the era of Kotlin 2, please leave a comment here or contact me at nillerr@gmail.com to discuss the details.

There is a single cost associated with Mockative, which is the `mockative.io` domain name coming in at around $40 / year up for renewal in about 2 months.

**Comment by TSampley** [comment]
I would gladly take over. I'm not sponsoring you for much at the moment, but $40/year is still cheaper year-to-year 😅

I greatly enjoy using your library and was just checking in on any new updates as I was about to set up another project to use mockative. I have only read about developing KSP plugins – never developed one myself, so I would appreciate any help you're willing to give on that front.

**Comment by Nillerr** [comment]
Hi @TSampley

After much consideration, I have returned to the project to put in the effort required to support Kotlin 2. I would still love to have more people contribute to the project, so if you have ideas feel free to submit them. Also, if you'd like input on your own KSP journey don't hesitate to contact me on #kotlinlang at https://kotlinlang.slack.com/team/U0N1TJZH8
