### ISSUE TITLE
Gradle error when installing mockative processor

### ISSUE THREAD

**Issue by Janglinator** [mockative/mockative#13]
I'm trying to install mockative to a KMM iOS/Android project, but running into the following issue:

```
Type mismatch: inferred type is Dependency? but Any was expected
```

Below is the gist of my build.gradle:

```
plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization") version "1.5.31"
    id("com.android.library")
    id("kotlin-android-extensions")
    id("com.google.devtools.ksp") version "1.5.31-1.0.0"
}

kotlin {
    sourceSets {
        val commonTest by getting {
            dependencies {
                implementation("io.mockative:mockative:1.0.6")
            }
        }
    }
}

dependencies {
    ksp(implementation("io.mockative:mockative-processor:1.0.6"))
}
```
However it's failing on the mockative-processor step

**Comment by Nillerr** [comment]
Hi @Janglinator 👋

From the error it sounds like you have some code in addition to the things you've added to your __build.gradle__ file, probably a class with a dependency called `Dependency`, is that correct?

If so, could you please attach the relevant source code and I'll have a look at it 😊

**Comment by Janglinator** [comment]
Unfortunately, as with most use cases of mockative, it's all NDA.  However I'll put together a simplified version and attach it later

**Comment by Nillerr** [comment]
Hi again Janglinator

I discovered an issue with the documentation in the README, and have updated it with new instructions.

Please use the following notation for adding `mockative-processor` to your project, and let me know if it fixes your issue:

```kotlin
dependencies {
    ksp("io.mockative:mockative-processor:1.0.7")
```

**Comment by Janglinator** [comment]
All is working as expected, thank you!
