### ISSUE TITLE
Overriding Stubs

### ISSUE THREAD

**Issue by mustafaozhan** [mockative/mockative#23]
In some use cases, developers need to override the previous stubs.
Ie. 

I have a test method that I want my mock to return some value, and after I made my assertion I want it to return some other value

```kotlin
    @Test
    fun methodName() {
        given(settingsRepository)
            .getter(settingsRepository::adFreeEndDate)
            .whenInvoked()
            .thenReturn(nowAsLong())
            
        assert(...)
        verify(...)

        given(settingsRepository)
            .getter(settingsRepository::adFreeEndDate)
            .whenInvoked()
            .thenReturn(nowAsLong() + DAY)

        assert(...)
        verify(...)
    }
```

Another use case, I have 11 test methods that I need to stub a mock, and only 2 of them to different values, since i can not override stubs, I have to have 11 times below:
```kotlin
     @Test
    fun methodName() {
        given(...)
        
        // rets of the implementation
    }
```

But if I am able to override the stubs, I could have this:
```kotlin
    @BeforeTest
    fun setup() {
        given(...)
    }
```
And only for 2 test methods this:
```kotlin
     @Test
    fun methodName() {
        given(...)
        
        // rets of the implementation
    }
```
So that the value stubbed in `@BeforeTest` will be overrided

**Comment by Nillerr** [comment]
This was considered initially before the first release, but I opted to not support it in favor of keeping the option open in case there was a demand for it. It can easily be implemented, so I will consider it once again.

For now, you should be able to work around it by using code like the following:

```kotlin
@Test
fun methodName()
    var adFreeEndDate = nowAsLong()

    given(settingsRepository)
        .getter(settingsRepository::adFreeEndDate)
        .whenInvoked()
        .then { adFreeEndDate }

    assert(...)
    verify(...)

    adFreeEndDate = nowAsLong() + DAY

    assert(...)
    verify(...)
}
```

You can also move `var adFreeEndDate` to a property of the test class, thus allowing you to have a default in a `@BeforeTest` function and replacing it in a `@Test` function. If you also wish to be able to throw exceptions, then you can declare a property holding a function instead, and swap that out for an implementation that throws the desire exception.

**Comment by mustafaozhan** [comment]
This approach seems to work for all the environments except native, it throws
`kotlin.native.concurrent.InvalidMutabilityException` when we try to use a global variable in the test class.

Logs are here: https://github.com/Oztechan/CCC/runs/4652698791?check_suite_focus=true#step:6:1721
Relevant PR: https://github.com/Oztechan/CCC/pull/367

**Comment by Nillerr** [comment]
I see. You'll have to wrap the property in an atomic reference, e.g. from [kotlinx.atomicfu](https://github.com/Kotlin/kotlinx.atomicfu) since the test class (or closure class) is being shared across threads.

**Comment by mustafaozhan** [comment]
I think it is too much workaround to just re-stub mocks. We shouldn't add libraries for doing it, I can duplicate the stubs for now per test method, but this is definitely something needed for a modern mocking library

**Comment by Nillerr** [comment]
I have decided to include this functionality in `v1.1.4`, which will be released later today 🙂

**Comment by mustafaozhan** [comment]
Hey @Nillerr thanks a lot for implementing it! I will try it as soon as possible 🙂
