### ISSUE TITLE
The 'ksp' configuration is deprecated in Kotlin Multiplatform projects

### ISSUE THREAD

**Issue by harmittaa** [mockative/mockative#26]
I am getting the following warning when building my KMM project with `mockative-processor` dependency:

> The 'ksp' configuration is deprecated in Kotlin Multiplatform projects. Please use target-specific configurations like 'kspJvm' instead.

Currently this doesn't seem to be causing any issues, but I'd like to get rid of it by switching to using the target-specific configurations. Any tips?

**Comment by harmittaa** [comment]
@FranAguilarRod thanks for the tip! That indeed worked. Much appreciated.

**Comment by Nillerr** [comment]
Hi @harmittaa 

Thanks for reporting the issue and apologies for not getting back to you sooner.

I have just released version `1.2.0` of Mockative, and I have updated the documentation in the README with a snippet that adds `mockative-processor` to all `ksp[...]Test` configurations, which can also solve your issue without explicitly specifying each configuration.
