### ISSUE TITLE
Mocking interface with more than 1 generic type does not work

### ISSUE THREAD

**Issue by spartanmarty** [mockative/mockative#27]
Hi,

thanks for this awesome lib. Unfortunately, I ran into a bug. 

When I try to mock interface looking for example like this:
`interface Example<INPUT : Any, OUTPUT : Any> {
    fun foo(key: INPUT): OUTPUT
}`

Build ends with an error:
e: ...shared/build/generated/ksp/android/androidDebugUnitTest/kotlin/io/mockative/GeneratedMocks.kt: (3, 219): Expecting a top level declaration

GeneratedMock.kt looks like this
`internal fun <INPUT, OUTPUT> mock(@Suppress("UNUSED_PARAMETER") type: kotlin.reflect.KClass<com.example.mockativetest.Example<INPUT, OUTPUT>>): com.example.mockativetest.Example<INPUT, OUTPUT> where INPUT : kotlin.Any where OUTPUT : kotlin.Any = com.example.mockativetest.ExampleMock<INPUT, OUTPUT>()`

Looks like a syntax error, there should be just one where, following generics should be separated by , :)

**Comment by Nillerr** [comment]
Hi @spartanmarty 

Apologies for not getting back to you sooner.

I have just released version `1.2.0` of Mockative, which features a complete rewrite of the code generation using [KotlinPoet](https://square.github.io/kotlinpoet/), which should resolve your issue.

**Comment by Nillerr** [comment]
Hi again

I discovered an issue in `1.2.0` causing the generated code to be invalid. I have resolved this issue in `1.2.1`, which is on its way out.
