### ISSUE TITLE
Generic TypeAlias not handled correctly

### ISSUE THREAD

**Issue by SamCosta1** [mockative/mockative#33]
Hi All

First of all it's great to have a library that works multiplatform! 
Just a quick issue I found while playing around with things.

Kotlin Version: 1.6.21
Mockative Version: 1.2.1

Typealiases which contain a generic don't seem to be handled correctly.
Minimal Example:

```
typealias MyTypeAlias<T> = List<T>

interface ToBeMocked {
    fun myFunction(): MyTypeAlias<Int>
}

class DemoTest() {
    @Mock
    private val myMock = mock(classOf<ToBeMocked>())
    @Test
    fun myTest() {
        // Fails before running
    }
}
```

Error:
```
e: shared/build/generated/ksp/android/androidDebugUnitTest/kotlin/com/apadmi/kotlinmultiplatformtest/feature/pokemon/ToBeMockedMock.Mockative.kt: (12, 37): One type argument expected for typealias MyTypeAlias<T> = List<T>
```

Generated Code:
```
public class ToBeMockedMock : Mockable(stubsUnitByDefault = false), ToBeMocked {
  public override fun myFunction(): MyTypeAlias =
      invoke<MyTypeAlias>(Invocation.Function("myFunction", listOf<Any?>()), false)

  public override fun equals(other: Any?): Boolean = invoke<Boolean>(Invocation.Function("equals",
      listOf<Any?>(other)), false)

  public override fun hashCode(): Int = invoke<Int>(Invocation.Function("hashCode", listOf<Any?>()),
      false)

  public override fun toString(): String = invoke<String>(Invocation.Function("toString",
      listOf<Any?>()), false)
}
```

Hope this is helpful!

**Comment by Nillerr** [comment]
Hi @SamCosta1 👋🏻 

Thanks for the thorough report. I'll investigate the issue.

**Comment by vitorhugods** [comment]
How fast are you, man?!?! 👏🏼

**Comment by SamCosta1** [comment]
Hi @Nillerr Thanks so much for being so quick!!!!

That solved the issue but I think possibly didn't fully support generic typaliases.

Please see the following example:

```
typealias MyTypeAlias<T> = Map<String, T>

interface ToBeMocked {
    fun myFunc(): MyTypeAlias<Int>
}

class DemoTest() {
    @Mock
    private val myMock = mock(classOf<ToBeMocked>())

    @Test
    fun myTest() {
        // Fails before running
    }
}
```

This works **correctly**

However. When I move the non test code (the interface and the typealias) out of `commonTest` and into the `commonMain` module. I get the following error.

`One type argument expected for typealias MyTypeAlias<T> = Map<String, T>`

With the following having been generated.

```
public class ToBeMockedMock : Mockable(stubsUnitByDefault = false), ToBeMocked {
  public override fun equals(other: Any?): Boolean = invoke<Boolean>(Invocation.Function("equals",
      listOf<Any?>(other)), false)

  public override fun hashCode(): Int = invoke<Int>(Invocation.Function("hashCode", listOf<Any?>()),
      false)

  public override fun myFunc(): MyTypeAlias<String, Int> =
      invoke<MyTypeAlias<String, Int>>(Invocation.Function("myFunc", listOf<Any?>()), false)

  public override fun toString(): String = invoke<String>(Invocation.Function("toString",
      listOf<Any?>()), false)
}
```

I hope this makes sense!

**Comment by Nillerr** [comment]
I see. I'll have a look at this case as well.

**Comment by SamCosta1** [comment]
That works perfectly now, thanks so much for being so fast! ❤️

**Comment by Nillerr** [comment]
Thank you for reporting the issue. I couldn't do it without the great work of the KotlinPoet team. The second issue you reported, with partial generic types, may well be a bug in KotlinPoet, so I'll consider submitting a PR to them to address it.
