### ISSUE TITLE
Cannot mock function with ambiguity 

### ISSUE THREAD

**Issue by AlexandreBrown** [mockative/mockative#36]
Hello,

I'm having trouble mocking the `putObject` suspend function from `aws.sdk.kotlin.services.s3.S3Client` (https://github.com/awslabs/aws-sdk-kotlin)  
  
I see that there are 2 functions with the same name but different input types.  

Maybe there is a way to specify the typing explicitly to help Mockative when doing the mocking ?  
  
The following does not work for now :   
```kotlin
given(s3Client).suspendFunction(s3Client::putObject)
		.whenInvokedWith(any())
		.thenReturn(createDummyResponse())
```

**Comment by Nillerr** [comment]
Hi @AlexandreBrown 

Under [Stubbing using Callable References](https://github.com/mockative/mockative#stubbing-using-callable-references) there's examples using `fun2<T1, T2>`, which is intended to be used for cases such as the one you're describing.

```kotlin

// When the function being stubbed has overloads with the same number of arguments, but different
// types, the type arguments must be specified using one of the `fun[0-9]` functions.
given(mock).function(mock::transformData, fun2<Data, String>())
    .whenInvokedWith(any(), any())
    .then { transformedData }
```

Let me know if this addresses your issue 🙂

**Comment by AlexandreBrown** [comment]
> Hi @AlexandreBrown
> 
> Under [Stubbing using Callable References](https://github.com/mockative/mockative#stubbing-using-callable-references) there's examples using `fun2<T1, T2>`, which is intended to be used for cases such as the one you're describing.
> 
> ```kotlin
> // When the function being stubbed has overloads with the same number of arguments, but different
> // types, the type arguments must be specified using one of the `fun[0-9]` functions.
> given(mock).function(mock::transformData, fun2<Data, String>())
>     .whenInvokedWith(any(), any())
>     .then { transformedData }
> ```
> 
> Let me know if this addresses your issue slightly_smiling_face

This fixed my issue, thank you so much!
