### ISSUE TITLE
Unresolved reference when creating mock for nested interface

### ISSUE THREAD

**Issue by robertwijas** [mockative/mockative#38]
I have:
```kotlin
class C {
  interface I {}
}
```

`@Mock` annotation generates:
```kotlin
internal class IMock : Mockable(stubsUnitByDefault = false), C.I {}
```

But the `mock` function is referencing `C.IMock`, not `IMock`:
```kotlin
internal fun mock(@Suppress("UNUSED_PARAMETER") type: KClass<C.I>): C.I = C.IMock()
```

Tested with version: 1.2.3

**Comment by Nillerr** [comment]
Hi again

I published [v1.2.4](https://github.com/mockative/mockative/releases/tag/v1.2.4) this morning which should address the issue you're having.

Let me know if this version fixes your issue 🙂
