### ISSUE TITLE
[Maintenance] Update workflows to use `macos-12` agents

### ISSUE THREAD

**Issue by Nillerr** [mockative/mockative#44]

**Comment by harmittaa** [comment]
@Nillerr I forked and updated to `macos-12`, the build action seems to work as expected:

https://github.com/harmittaa/mockative/actions/runs/3060447417/jobs/4938974278#step:1:4

Do you happen to know of any easy ways to test the `Release` workflow as well, besides that I create Sonatype credentials and run it against them?
