### ISSUE TITLE
[Proposal] Generate `mock<T>()` instead of `mock(KClass<T>)`

### ISSUE THREAD

**Issue by hoc081098** [mockative/mockative#46]

**Comment by Nillerr** [comment]
Thank you for the suggestion @hoc081098.

As much as I wanted to do it this way it's unfortunately not possible with the way Kotlin resolves function overloads.

**Comment by hoc081098** [comment]
Thanks. I got it 😂

**Comment by pal03377** [comment]
Could this be possible using [`reified`](https://kotlinlang.org/docs/inline-functions.html#reified-type-parameters)? Pardon my ignorance if I am completely wrong here (I just stumbled over this feature and have no experience), but I was able to write a helper function for myself like this:
```
inline fun <reified T : Any> makeMock(): T = mock(classOf())
```

...and use it like this:
```
@Mock
private val task = makeMock<Task>()
```

Couldn't that make `mock<T>()` work?

(Thanks for this nice mocking library by the way, I'm really enjoying using it!)

**Comment by pal03377** [comment]
Sorry for another message, it didn't actually work - the mock wasn't generated :-(
