### ISSUE TITLE
Trying to use the library results in `A mock for the type X was not generated` error.

### ISSUE THREAD

**Issue by aminecmi** [mockative/mockative#47]
Hello,

I'm trying to use the library to test some shared kotlin multiplatform code, and I keep having the `A mock for the type X was not generated` error.

I think that the problem is, if I want to mock `class A(val xxx: X) {}`, (with `@Mock private val a = mock(classOf<A>())`) I need to mock `X` too.

Is this right ?

In my case, `X` is another library's class, that itself uses other classes.

Is there a simple way to handle this ?

Thanks.

**Comment by Nillerr** [comment]
Hi @aminecmi

Thank you for using Mockative.

Unfortunately, mocking classes is not supported, which seems to be what you're experiencing. Can you confirm that you are indeed attempting to mock a `class` and not an `interface`?

**Comment by aminecmi** [comment]
Hi @Nillerr 

Yes, I was trying to mock a `class`.

I didn't see the `Mocking of interfaces only` in the readme.

Sorry about that, I'll have to find something else.

**Comment by Nillerr** [comment]
No worries. Mocking of classes has been on my to-do list of investigations for a long while now, but I just haven't had the time to dig into it. I know what needs to be done, but there's simply haven't found enough time to give it a proper go yet.
