### ISSUE TITLE
Provide shorthand for passing any() to .whenInvokedWith

### ISSUE THREAD

**Issue by dalewking** [mockative/mockative#58]
If I have an interface function that for example takes 3 arguments and I want to set up mock where I don't care what is passed I have to say:

```
   given(myMock).function(::myFunction).whenInvokedWith(any(), any(), any())
```
or say I only care that the value passed for parameter 3 is true:

```
   given(myMock).function(::myFunction).whenInvokedWith(any(), any(), eq(true))
```

It would be nice to not have to type all of those any() expressions. The simple answer is make any() the default value for the parameters as in:

```
    fun whenInvokedWith(p1: Matcher<P1> = any(), p2: Matcher<P2> = any(), p3: Matcher<P3> = any()): ResultBuilder {
```

Then those 2 cases become:
```
   given(myMock).function(::myFunction).whenInvokedWith()
   given(myMock).function(::myFunction).whenInvokedWith(p3 = eq(true))
```

`whenInvokedWith()` is kind of ugly so I would add a `whenInvoked()` that is syntactic sugar for it

**Comment by Nillerr** [comment]
Hi @dalewking 

Thank you for your patience and the excellent suggestion. I have included your proposal in [v1.4.0](https://github.com/mockative/mockative/releases/tag/v1.4.0) which I released this morning.
