### ISSUE TITLE
Unexpected result when calling `wasInvoked()` with default parameters

### ISSUE THREAD

**Issue by vitorhugods** [mockative/mockative#62]
Given `myMock.foo()` is _**not**_ called. The verifications below succeed:

```kotlin
verify(myMock)
    .function(myMock::foo)
    .wasInvoked()


verify(myMock)
    .function(myMock::foo)
    .wasInvoked(atMost = 10.times)
```

However, it is quite unexpected. 
As the "human readable" code doesn't reflect what it actually does under the hood.

It reads like:

> Verify that this object's
> function named foo
> was invoked

But it wasn't.

Mockito and MockK would have this failing, so I was a bit surprised when I noticed this isn't the case here.

I traced the cause down the `wasInvoked` signature:

- [Default constructor](https://github.com/mockative/mockative/blob/1f5837e15863be460ca9ada36aee4e867b93cafc/mockative/src/commonMain/kotlin/io/mockative/Verification.kt#L18) uses `null` as the `atLeast` parameter
- [`RangeVerifier` uses `0` for `atLeast` when it is `null`](https://github.com/mockative/mockative/blob/1f5837e15863be460ca9ada36aee4e867b93cafc/mockative/src/commonMain/kotlin/io/mockative/RangeVerifier.kt#L12)

My proposal is having `atLeast = once` as the default. Because that's pretty much what one could expect from calling this function.

I'm raising a PR soon, just creating this issue before-hand in order to have this fully documented.

Also, I guess this could be a "breaking" change? I'm not sure. Looks more like a bugfix to me 🤔

**Comment by vitorhugods** [comment]
It could be a breaking change for people that used only the `atMost`.

Example:
```kotlin
.wasInvoked(atMost = 10.times)
```


However, verifying that something `wasInvoked()` and it succeeding when it wasn't is also wrong 🤔.

```kotlin
.wasInvoked()
```


I'd settle with something like:

```kotlin
.wasMaybeInvoked(atMost = 10.times)
```

For the cases where it may or may not have been invoked up to a certain amount of times. Instead of `wasInvoked(...)` when it wasn't.

**Comment by SamC-Apadmi** [comment]
+1 On this. Was about to raise this issue myself.

> My proposal is having atLeast = once as the default. Because that's pretty much what one could expect from calling this function.

I think this is the correct solution. Yes it's a breaking change, but I think it should be personally.

**Comment by Nillerr** [comment]
Thank you for identifying this issue @vitorhugods 

This is definitely not working as intended, and your PR is very welcomed. Let's pick up the discussion on your PR 😊
