### ISSUE TITLE
Documentation should emphasize the correct way to use callable references

### ISSUE THREAD

**Issue by dalewking** [mockative/mockative#65]
Ran into an issue when trying to use callable reference functions(https://github.com/mockative/mockative#stubbing-using-callable-references) and I think it is an issue that the documentation could call out better to prevent others from running into the same issue. It isn't a bug in the Mockative implementation, but a trap that a user can fall into, though there may be something that you could do in the implementation to prevent it.

So let's say I have an interface like this:

```
interface Foo {
    operator suspend fun invoke(x : Int): Int
}
```

And I declare a mock for it:
```
    @Mock
    val foo = mock(classOf<Foo>())

```

I tried specifying behavior for it like this:
```
        given(foo)
            .suspendFunction(Foo::invoke)
            .whenInvokedWith()
            .thenReturn(5)
```

But that doesn't work and will fail to find the behavior specified because the suspendFunction call should be:
```
            .suspendFunction(foo::invoke)
```

`Foo:invoke` is a 2 parameter function reference where the first parameter is the instance to call it on, while `foo::invoke` is a 1 parameter function where it is already bound to the instance.

The documentation does show it correctly, but should probably call out this subtlety to prevent errors if there is no way to support the other

**Comment by dalewking** [comment]
I view version 2 as HUGE downgrade.

The ability to use callable references was a huge advantage of Mockative. They allowed you to set up the behavior for a suspending call without having to be in a suspending function to do so. Requiring users to be in a suspend function to set up the behavior is a major problem.

The other huge downgrade from version 2 is the removal of the `then` function that takes a type-safe lambda (i.e. this version from the readme):
```
| `then(block: (P1, P..., PN) -> R)` | Invokes the specified block. The arguments passed to the block are the arguments passed to the invocation. |
```

Now you just get an untyped array of parameters.

So we will likely be sticking with the old version.

**Comment by Nillerr** [comment]
Thank you for your feedback @dalewking.

Your comments have made me consider whether I made a rushed decision by breaking the backward compatibility of Mockative in version 2, while also sacrificing certain features of the framework.

I will take a step back and reflect on the process and consider how to progress from here on out, whether it means maintaining both APIs of Mockative or reverting my choices in Mockative 2 in a new version of Mockative such as 3.

Regardless of what it ends up being, I value your feedback and will look into incorporating whichever new features of Mockative 2 I can in a new incremental release of Mockative 1, so you guys won't miss out. I will also add some documentation to the `main` branch about the API of Mockative 1, and include your suggestions about improving the documentation in that document.
