### ISSUE TITLE
Overload resolution ambiguity: `SuspendResultBuilder.invokes` and `ResultBuilder.invokes`

### ISSUE THREAD

**Issue by hoc081098** [mockative/mockative#73]
- Code (similar to readme.md), but it does not work :))
```kotlin
coEvery { repoItemApi.searchRepoItems(term, page) }
  .invokes { FAKE_REPO_ITEMS_SEARCH_RESPONSE.right() }
```

- Error
```
Overload resolution ambiguity. All these functions match.
public open fun invokes(block: suspend () → Either<Throwable, RepoItemsSearchResponse>): Unit defined in io.mockative.SuspendResultBuilder
public final fun invokes(block: suspend (arguments: Array<Any?>) → Either<Throwable, RepoItemsSearchResponse>): Unit defined in io.mockative.SuspendResultBuilder
```

- Currently, there are two `invokes` functions in `SuspendResultBuilder`:
   - `fun invokes(block: suspend (arguments: Array<Any?>) -> R)` (1).
   - `override fun invokes(block: suspend () -> R)` (2).

When we want to use (2), but (1) has higher priority, we have to use it like this `invokes { _ -> }`. Without `_ -> ` does not work.
IMO, could we provide (1) with another name to avoid the ambiguity? Maybe `invokesWithArgs` 😁.
`ResultBuilder` has the same thing.

Thank you so much 🙏

**Comment by dalewking** [comment]
It seems to me that the `override fun invokes(block: suspend () -> R)` does not provide any real value. If it didn't exist we would just have the lambda with an implicit `it` parameter of the args that would be ignored. If you were not using and lamda and instead were using a function reference to a function that did not take a parameter Kotlin can handle passing it.

i am working around it by using a function like this instead:
```
    infix fun <T> SuspendResultBuilder<T>.invoke (block: suspend (Array<Any?>) -> T) = invokes(block)
```
