### ISSUE TITLE
kotlin 2.0 support

### ISSUE THREAD

**Issue by hanrw** [mockative/mockative#74]
I got some errors below after upgraded to kotlin 2.0 beta:
```
clear[macosArm64] FAILED
    io.mockative.NoSuchMockException at /opt/buildAgent/work/6285e88d8d1c1e7f/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Throwable.kt:28
```

**Comment by Nillerr** [comment]
Hi @hanrw

Thank you for using Mockative. I'm sorry it has taken me this long to respond to your issue.

Kotlin 2.0 is coming up and will unfortunately introduce changes that break a quirk used by Mockative. I have some ideas for how to overcome those changes, which I will look into in the coming weeks.

**Comment by sergeys-opera** [comment]
I'm also facing the same issue after upgrading to K2. Note that the K2 RC is already available: https://kotlinlang.org/docs/whatsnew-eap.html#new-kotlin-k2-compiler-updates

**Comment by Clemodd** [comment]
> I'm also facing the same issue after upgrading to K2. Note that the K2 RC is already available: https://kotlinlang.org/docs/whatsnew-eap.html#new-kotlin-k2-compiler-updates

Up, me too... :(

**Comment by Vivecstel** [comment]
same

**Comment by Nillerr** [comment]
Hey people 👋🏻!

I am tracking the challenges and work for K2 and Kotlin 2.0 at https://github.com/mockative/mockative/issues/116. Unfortunately, the K2 compiler will introduce a change that breaks how Mockative generates mocks for code under test. I have ideas for steps to mitigate this, which I will explore throughout the coming week. I hope to have a solution ready for the release of Kotlin 2 with K2 before the expected launch in June.

**Comment by TWiStErRob** [comment]
Is there a workaround? i.e. using Kotlin Gradle Plugin 2.0 in the project, and making it work? I tried
```gradle
compilerOptions.languageVersion = KotlinVersion.fromVersion("1.9")
```
but it didn't make a difference.

(The project is mixed, so only 1-2 modules use mockative, but it's keeping me from upgrading the rest.)

**Comment by theolm** [comment]
Any updates here?
I work on a project with 2k+ tests using Mokative. This lib is currently holding back the update to Kotlin 2.0 and Compose 1.6.10 (and we need this update). The team is considering refactoring the tests to remove the lib. =/

**Comment by hanrw** [comment]
> Any updates here?
> 
> I work on a project with 2k+ tests using Mokative. This lib is currently holding back the update to Kotlin 2.0 and Compose 1.6.10 (and we need this update). The team is considering refactoring the tests to remove the lib. =/

was migrated to mockito and only test for jvm

**Comment by Nillerr** [comment]
Mockative 3 has been released with support for Kotlin 2
