### ISSUE TITLE
Unable to mock an interface with method marked with OptIn annotation

### ISSUE THREAD

**Issue by ArseniyAbramenko** [mockative/mockative#75]
For example, we have an annotation:

```
@RequiresOptIn(level = RequiresOptIn.Level.ERROR)
@Retention(AnnotationRetention.BINARY)
annotation class SomeRequirementOptIn
```
Then we have an interface, containing method, marked with this annotation:

```
interface MyInterface {

    @SomeRequirementOptIn
    suspend fun process(input: String): String
}
```
When we mock this interface, the following code is generated by Mockative:

```
public class MyInterfaceMock : Mockable(stubsUnitByDefault = true), MyInterface {

  override suspend fun process(input: String): String =
      suspend<String>(Invocation.Function("process", listOf<Any?>(`input`)), false)
}
```

And when we try to run the test with this mock, we get a compilation error in generated file:

Base declaration of supertype 'MyInterface' needs opt-in. The declaration override must be annotated with '@com.somepackage.SomeRequirementOptIn' or '@OptIn(com.somepackage.SomeRequirementOptIn::class)'

So we need some way to provide an OptIn annotation to the code generated by Mockative.

**Comment by magnumrocha** [comment]
I'm having this same problem with some iOS Kotlin bindings objects that need the Annotation: `@OptIn(ExperimentalForeignApi::class)`

The compilation fails with:
```
...ksp/iosSimulatorArm64/iosSimulatorArm64Test/kotlin/my/package/SomeClassMock.kt:12:16 Base declaration of supertype 'ReachabilityInteractor' needs opt-in. The declaration override must be annotated with '@kotlinx.cinterop.ExperimentalForeignApi' or '@OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)'
```

**Comment by Nillerr** [comment]
Hi!

Apologies for my hiatus from this project. I have investigated this issue and can conclude that with the way Mockative currently works, there is unfortunately no way to read the `@OptIn` annotations from the types of the mock classes we're generating.

As a workaround, you can a global opt-in through a compiler argument:

```kotlin
kotlin {
    compilerOptions {
        freeCompilerArgs.add("-opt-in=kotlinx.cinterop.ExperimentalForeignApi")
    }
}
```

I might have to fundamentally change the way Mockative reads the types in generates mocks for as a result of Kotlin 2.0, in which case reading these annotations may well be possible.

**Comment by Nillerr** [comment]
Hi again. I will add support for specifying the `@OptIn` annotation on mocks using KSP arguments like so:

```kotlin
ksp {
    arg("io.mockative:mockative:opt-in:io.github.OptInType", "kotlinx.cinterop.ExperimentalForeignApi")
    arg("io.mockative:mockative:opt-in:io.github.*", "kotlin.ExperimentalStdlibApi")
    arg("io.mockative:mockative:opt-in", "kotlin.ExperimentalUnsignedTypes")
}
```

This will result in generating a mock class with the following annotation:

```kotlin
@OptIn(
  ExperimentalUnsignedTypes::class,
  ExperimentalForeignApi::class,
  ExperimentalStdlibApi::class,
)
public class OptInTypeMock
```

I will include this in the next release of Mockative
