### ISSUE TITLE
Error when name of interface/class to be mocked is too long

### ISSUE THREAD

**Issue by DanielWeidensdoerfer** [mockative/mockative#99]
Given this mock
`
    @Mock
    private val mockResetPasswordDataValidator = mock(classOf<IResetPasswordDataValidator>())
`

On test startup a compilation error occures

`IResetPasswordDataValidator.Mockative.kt:10:5 Expecting an element`

content of generated class is

> public fun mock(@Suppress("UNUSED_PARAMETER") type: KClass<IResetPasswordDataValidator>):
>     IResetPasswordDataValidator = configure(IResetPasswordDataValidatorMock()) { stubsUnitByDefault
>     = true }

Notice the line break after `stubsUnitByDefault`.

Removing the line break removes the error. On test restart the file is regenerated with same line break though.

Line break probably happens when interface/class to be mocked is to long. Making the name shorter solves the problem (inacceptable though ;) )

**Comment by vitorhugods** [comment]
Dupe of:
- https://github.com/mockative/mockative/issues/88

It was introduced in `2.1.0` and solved in `2.2.0`

**Comment by DanielWeidensdoerfer** [comment]
I updated too `2.2.0` and still happens

**Comment by vitorhugods** [comment]
> I updated too `2.2.0` and still happens

Make sure you're using the `2.2.0` KSP processor:
```kotlin
dependencies {
    configurations
        .filter { it.name.startsWith("ksp") && it.name.contains("Test") }
        .forEach {
            add(it.name, "io.mockative:mockative-processor:2.2.0")
        }
}
```

As the fix was in the processor/code-generation, and not in the runtime (`io.mockative:mockative:2.2.0`)

**Comment by DanielWeidensdoerfer** [comment]
Now it works, thanks
